[build]
  base = "admin-dashboard"
  command = "npm run build"
  publish = "dist"

# ❌ Do NOT set VITE_API_URL in production — client should use '/api' via api.ts
# [build.environment]
#   VITE_API_URL = "https://domy-backend.vercel.app/api"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://domy-backend.vercel.app/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

# SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
