[build]
  base = "admin-dashboard"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "https://domy-backend-git-em-kokojs-projects.vercel.app/api"

[[redirects]]
  from = "/api/*"
  to = "https://domy-backend-git-em-kokojs-projects.vercel.app/api/:splat"
  status = 200
  force = true

# Handle client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
