[build]
  base = "admin-dashboard"
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_URL = "/api"

[[redirects]]
  from = "/api/*"
  to = "https://domy-backend.vercel.app/api/:splat"
  status = 200
  force = true
